---
apiVersion: v2
name: valheim
description: A Helm Chart for Valheim
type: application
version: 0.4.11
appVersion: 3.5.0
maintainers:
  - name: barrelmaker97
    email: nolancooper97@gmail.com
    url: barrelmaker.dev
