---
apiVersion: v2
name: jellyfin
description: A Helm Chart for Jellyfin
type: application
version: 0.5.3
appVersion: 10.11.2
maintainers:
  - name: barrelmaker97
    email: nolancooper97@gmail.com
    url: barrelmaker.dev
