---
apiVersion: v2
name: minecraft
description: A Helm Chart for Minecraft
type: application
version: 0.8.28
appVersion: 2026.1.2-java21-alpine
maintainers:
  - name: barrelmaker97
    email: nolancooper97@gmail.com
    url: barrelmaker.dev
