---
apiVersion: v2
name: website
description: A Helm Chart for a website
type: application
version: 0.5.8
appVersion: 1.28.0-alpine
maintainers:
  - name: barrelmaker97
    email: nolancooper97@gmail.com
    url: barrelmaker.dev
