---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obscura.fullname" . }}
  labels:
    {{- include "obscura.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "obscura.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "obscura.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "obscura.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.minio.enabled }}
      initContainers:
        - name: create-bucket
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          command:
            - /bin/sh
            - -c
            - |
              sleep 5;
              /usr/bin/mc alias set local {{ include "obscura.storageEndpoint" . }} {{ include "obscura.storageAccessKey" . }} {{ include "obscura.storageSecretKey" . }};
              if ! /usr/bin/mc ls local/{{ .Values.obscura.storage.bucket }} > /dev/null 2>&1; then
                /usr/bin/mc mb local/{{ .Values.obscura.storage.bucket }};
              fi
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "obscura.fullname" . }}-config
          env:
            - name: OBSCURA_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "obscura.fullname" . }}-secret
                  key: database-url
            - name: OBSCURA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "obscura.fullname" . }}-secret
                  key: jwt-secret
            - name: OBSCURA_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "obscura.fullname" . }}-secret
                  key: storage-access-key
            - name: OBSCURA_STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "obscura.fullname" . }}-secret
                  key: storage-secret-key
          ports:
            - name: http
              containerPort: {{ .Values.obscura.server.port }}
              protocol: TCP
            - name: mgmt
              containerPort: {{ .Values.obscura.server.mgmtPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: mgmt
          readinessProbe:
            httpGet:
              path: /readyz
              port: mgmt
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
