apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obscura.fullname" . }}-secret
  labels:
    {{- include "obscura.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "obscura.databaseUrl" . | b64enc | quote }}
  jwt-secret: {{ .Values.obscura.auth.jwtSecret | b64enc | quote }}
  s3-access-key: {{ include "obscura.s3AccessKey" . | b64enc | quote }}
  s3-secret-key: {{ include "obscura.s3SecretKey" . | b64enc | quote }}
