apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obscura.fullname" . }}-secret
  labels:
    {{- include "obscura.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.obscura.databaseUrl | b64enc | quote }}
  jwt-secret: {{ .Values.obscura.jwtSecret | b64enc | quote }}
