apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obscura.fullname" . }}-secret
  labels:
    {{- include "obscura.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "obscura.databaseUrl" . | b64enc | quote }}
  pubsub-url: {{ include "obscura.pubsubUrl" . | b64enc | quote }}
  jwt-secret: {{ .Values.obscura.auth.jwtSecret | b64enc | quote }}
  storage-access-key: {{ include "obscura.storageAccessKey" . | b64enc | quote }}
  storage-secret-key: {{ include "obscura.storageSecretKey" . | b64enc | quote }}