apiVersion: v1
kind: Service
metadata:
  name: {{ include "obscura.fullname" . }}-mgmt
  labels:
    {{- include "obscura.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.obscura.server.mgmtPort }}
      targetPort: mgmt
      protocol: TCP
      name: mgmt
  selector:
    {{- include "obscura.selectorLabels" . | nindent 4 }}
