---
apiVersion: v2
name: obscura
description: A Helm chart for Obscura Server
type: application
version: 0.1.8
appVersion: 0.3.7
maintainers:
  - name: barrelmaker97
    email: nolancooper97@gmail.com
    url: barrelmaker.dev
dependencies:
  - name: postgresql
    version: ~18.2.0
    repository: https://charts.bitnami.com/bitnami
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
